services:
  postgres:
    image: postgres:16
    container_name: apiaggregator_postgres
    environment:
      POSTGRES_DB: apiaggregator
      POSTGRES_USER: apiaggregator_user
      POSTGRES_PASSWORD: apiaggregator_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: